@startuml

package "model" {

    interface Ontrack {
        getProjectByID(id: Int): Project
        findProjectByName(name: String): Project?
    }

    interface Project {
        branches: List<Branch>
    }

    interface Branch {
        project: Project
    }

}

package "json" {



}

@enduml