@startuml

cloud Ontrack {
    package OntrackAPI
}

cloud Client {
    component ClientCode
    node KDSLDockerRunner {
        component KDSLRunner
        package KDSL {
            component "kdsl-model" as KDSLModel
            component "extension-kdsl" as ExtensionKDSL
        }
    }
}

ClientCode -right-> KDSLDockerRunner: docker run

ExtensionKDSL --> KDSLModel
KDSLRunner -right-> KDSL

KDSLModel -right-> OntrackAPI: http

@enduml