-- 24. Bulk build links

CREATE TABLE PROJECT_PACKAGE
(
  ID           SERIAL PRIMARY KEY NOT NULL,
  PROJECT      INTEGER            NOT NULL,
  PACKAGE_TYPE VARCHAR(150)       NOT NULL,
  PACKAGE_ID   VARCHAR(400)       NOT NULL,
  CONSTRAINT PROJECT_PACKAGE_FK_PROJECT FOREIGN KEY (PROJECT) REFERENCES PROJECTS (ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS PROJECT_PACKAGE_IX_PACKAGE ON PROJECT_PACKAGE (PACKAGE_TYPE, PACKAGE_ID);
